Implement abort for JoinHandle
In our code we actually call `abort` method on tokio's `JoinHandle` struct, once I tried to use shuttle, I saw that calling `abort` causes another panic

```bash
...
thread 'main' panicked at 'not implemented', /Users/koshelev/.cargo/registry/src/github.com-1ecc6299db9ec823/shuttle-0.4.1/src/future/mod.rs:42:9
stack backtrace:
```

Not sure if this is the right way to implement it, happy to iterate on that as well as adding more tests if required.