Fix clippy warnings (#165)
* Fix two instances of elided_named_lifetimes warning

`cargo check` on 1.83 currently fails due to the use of `#[deny(warnings)]`
because of two occurrences of the `elided_named_lifetimes` warning,
as shown below:

```
error: elided lifetime has a name
  --> src/lazy_static.rs:48:34
   |
48 |     pub fn get(&'static self) -> &T {
   |                                  ^ this elided lifetime gets resolved as `'static`
   |
note: the lint level is defined here
  --> src/lib.rs:1:9
   |
1  | #![deny(warnings, missing_debug_implementations, missing_docs)]
   |         ^^^^^^^^
   = note: `#[deny(elided_named_lifetimes)]` implied by `#[deny(warnings)]`
help: consider specifying it explicitly
   |
48 |     pub fn get(&'static self) -> &'static T {
   |                                   +++++++
```

This commit fixes both of the warnings by applying the recommended
fix.  Since the elided lifetime is resolved to be `'static` anyways,
there's no change in behavior.

* Fix additional clippy warnings

This commit fixes a few Clippy warnings that are set to `deny` and
therefore cause CI checks in pull requests to fail.

I verified that `cargo clippy --all-targets --all-features` succeeds
(with no warnings nor errors) after the fixes.